/**
 * BuildMyHome - Notification Model
 * Mongoose schema for in-app notifications
 * 
 * AI-READY: Includes aiMetadata and vectorEmbeddingsRef fields
 * for future ML integrations (smart prioritization, auto-categorization, etc.)
 */

const mongoose = require('mongoose');
const { NOTIFICATION_TYPES } = require('../../constants/enums');

const notificationSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  type: {
    type: String,
    enum: Object.values(NOTIFICATION_TYPES),
    required: true,
  },
  title: {
    type: String,
    required: [true, 'Notification title is required'],
    trim: true,
    maxlength: [200, 'Title cannot exceed 200 characters'],
  },
  message: {
    type: String,
    required: [true, 'Notification message is required'],
    maxlength: [1000, 'Message cannot exceed 1000 characters'],
  },
  data: {
    type: mongoose.Schema.Types.Mixed,
    default: {},
  },
  priority: {
    type: String,
    enum: ['low', 'normal', 'high', 'urgent'],
    default: 'normal',
  },
  isRead: {
    type: Boolean,
    default: false,
  },
  readAt: {
    type: Date,
  },
  isArchived: {
    type: Boolean,
    default: false,
  },
  expiresAt: {
    type: Date,
  },
  // Source tracking for analytics
  source: {
    type: String,
    enum: ['system', 'booking', 'chat', 'review', 'design', 'admin', 'promotion'],
    default: 'system',
  },
  actionUrl: {
    type: String,
    maxlength: 500,
  },
  // --- AI-READY FIELDS ---
  aiMetadata: {
    priorityScore: { type: Number, min: 0, max: 1 },
    category: { type: String },
    isAutoGenerated: { type: Boolean, default: false },
    userActionPrediction: { type: String }, // e.g. 'will_click', 'will_dismiss'
    sentimentScore: { type: Number, min: -1, max: 1 },
    processedAt: { type: Date },
    confidence: { type: Number, min: 0, max: 1 },
  },
  vectorEmbeddingsRef: {
    provider: { type: String },
    embeddingId: { type: String },
    lastSyncedAt: { type: Date },
  },
}, {
  timestamps: true,
  toJSON: {
    virtuals: true,
    transform: (doc, ret) => {
      ret.id = ret._id;
      delete ret._id;
      delete ret.__v;
      return ret;
    },
  },
});

// --- Indexes ---
notificationSchema.index({ userId: 1, createdAt: -1 });
notificationSchema.index({ userId: 1, isRead: 1 });
notificationSchema.index({ type: 1, createdAt: -1 });
notificationSchema.index({ isRead: 1, createdAt: -1 });
notificationSchema.index({ priority: 1, createdAt: -1 });
notificationSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });
notificationSchema.index({ 'aiMetadata.priorityScore': -1 });
notificationSchema.index({ source: 1, createdAt: -1 });

// Compound indexes for dashboard queries
notificationSchema.index({ userId: 1, isRead: 1, createdAt: -1 });
notificationSchema.index({ userId: 1, type: 1, createdAt: -1 });

// --- Statics ---

/**
 * Get notifications for a user with pagination
 */
notificationSchema.statics.getUserNotifications = async function (userId, options = {}) {
  const { page = 1, limit = 20, unreadOnly = false, types = [] } = options;
  
  const query = { userId, isArchived: false };
  if (unreadOnly) query.isRead = false;
  if (types.length > 0) query.type = { $in: types };

  const skip = (page - 1) * limit;
  
  const [notifications, total, unreadCount] = await Promise.all([
    this.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .lean(),
    this.countDocuments(query),
    this.countDocuments({ userId, isRead: false, isArchived: false }),
  ]);

  return {
    notifications,
    unreadCount,
    pagination: { page, limit, total, totalPages: Math.ceil(total / limit) },
  };
};

/**
 * Mark all notifications as read for a user
 */
notificationSchema.statics.markAllAsRead = async function (userId) {
  return this.updateMany(
    { userId, isRead: false },
    { $set: { isRead: true, readAt: new Date() } }
  );
};

/**
 * Get unread count for a user
 */
notificationSchema.statics.getUnreadCount = async function (userId) {
  return this.countDocuments({ userId, isRead: false, isArchived: false });
};

// --- Pre-save ---
notificationSchema.pre('save', function (next) {
  // Auto-set readAt when marking as read
  if (this.isModified('isRead') && this.isRead && !this.readAt) {
    this.readAt = new Date();
  }
  next();
});

const Notification = mongoose.model('Notification', notificationSchema);

module.exports = Notification;

