/**
 * BuildMyHome - Chat & Message Models
 * Mongoose schemas for conversations and messages
 * 
 * AI-READY: Includes aiMetadata and vectorEmbeddingsRef fields
 * for future ML integrations (sentiment analysis, auto-responses, etc.)
 */

const mongoose = require('mongoose');
const { CHAT_TYPES, MESSAGE_TYPES } = require('../../constants/enums');

// ============================================================
// Message Schema
// ============================================================
const messageSchema = new mongoose.Schema({
  chatId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Chat',
    required: true,
    index: true,
  },
  senderId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  messageType: {
    type: String,
    enum: Object.values(MESSAGE_TYPES),
    default: MESSAGE_TYPES.TEXT,
  },
  content: {
    type: String,
    required: true,
    maxlength: [10000, 'Message content cannot exceed 10000 characters'],
  },
  attachments: [{
    url: { type: String, required: true },
    name: { type: String },
    type: { type: String },
    size: { type: Number },
    thumbnailUrl: { type: String },
  }],
  readBy: [{
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    readAt: {
      type: Date,
      default: Date.now,
    },
  }],
  // Edits and deletion tracking
  editedAt: { type: Date },
  isDeleted: { type: Boolean, default: false },
  deletedFor: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  // --- AI-READY FIELDS ---
  aiMetadata: {
    sentimentScore: { type: Number, min: -1, max: 1 },
    urgencyScore: { type: Number, min: 0, max: 1 },
    isAutoGenerated: { type: Boolean, default: false },
    moderationFlags: [String],
    categories: [String],
    confidence: { type: Number, min: 0, max: 1 },
    lastProcessedAt: { type: Date },
  },
  vectorEmbeddingsRef: {
    provider: { type: String }, // e.g. 'openai', 'pinecone', 'chroma'
    embeddingId: { type: String },
    lastSyncedAt: { type: Date },
  },
}, {
  timestamps: true,
  toJSON: {
    virtuals: true,
    transform: (doc, ret) => {
      ret.id = ret._id;
      delete ret._id;
      delete ret.__v;
      return ret;
    },
  },
});

// --- Message Indexes ---
messageSchema.index({ chatId: 1, createdAt: -1 });
messageSchema.index({ senderId: 1, createdAt: -1 });
messageSchema.index({ 'readBy.userId': 1 });
messageSchema.index({ 'aiMetadata.sentimentScore': 1 });
messageSchema.index({ 'aiMetadata.moderationFlags': 1 });
messageSchema.index({ createdAt: -1 });
messageSchema.index({ 'attachments.type': 1 });

// Virtual: is read by specific user
messageSchema.virtual('isReadBy').get(function () {
  return function (userId) {
    return this.readBy.some(r => r.userId.toString() === userId.toString());
  };
});

// ============================================================
// Chat Schema (Conversation)
// ============================================================
const chatSchema = new mongoose.Schema({
  participants: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  }],
  type: {
    type: String,
    enum: Object.values(CHAT_TYPES),
    default: CHAT_TYPES.DIRECT,
  },
  name: {
    type: String,
    trim: true,
    maxlength: [100, 'Chat name cannot exceed 100 characters'],
  },
  lastMessage: {
    message: { type: String, maxlength: 200 },
    senderId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    sentAt: { type: Date },
    messageType: { type: String, enum: Object.values(MESSAGE_TYPES) },
  },
  bookingId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Booking',
  },
  unreadCount: {
    type: Map,
    of: Number,
    default: {},
  },
  isActive: {
    type: Boolean,
    default: true,
  },
  // --- AI-READY FIELDS ---
  aiMetadata: {
    summary: { type: String },
    lastAnalyzedAt: { type: Date },
    participantSentiment: { type: Map, of: Number },
    topicCategories: [String],
    actionItems: [String],
    confidence: { type: Number, min: 0, max: 1 },
  },
  vectorEmbeddingsRef: {
    provider: { type: String },
    embeddingId: { type: String },
    lastSyncedAt: { type: Date },
  },
}, {
  timestamps: true,
  toJSON: {
    virtuals: true,
    transform: (doc, ret) => {
      ret.id = ret._id;
      delete ret._id;
      delete ret.__v;
      return ret;
    },
  },
});

// --- Chat Indexes ---
chatSchema.index({ participants: 1 });
chatSchema.index({ type: 1, isActive: 1 });
chatSchema.index({ bookingId: 1 }, { sparse: true });
chatSchema.index({ updatedAt: -1 });
chatSchema.index({ 'aiMetadata.topicCategories': 1 });
// Compound index for participant + active chat lookups
chatSchema.index({ participants: 1, isActive: 1, updatedAt: -1 });

// Static: Get or create direct chat
chatSchema.statics.getOrCreateDirect = async function (userId1, userId2, bookingId = null) {
  const query = {
    type: CHAT_TYPES.DIRECT,
    participants: { $all: [userId1, userId2], $size: 2 },
  };
  if (bookingId) query.bookingId = bookingId;

  let chat = await this.findOne(query);
  if (!chat) {
    chat = await this.create({
      participants: [userId1, userId2],
      type: bookingId ? CHAT_TYPES.BOOKING : CHAT_TYPES.DIRECT,
      bookingId,
    });
  }
  return chat;
};

// Static: Get user chats with unread counts
chatSchema.statics.getUserChats = async function (userId, options = {}) {
  const { page = 1, limit = 20 } = options;
  const skip = (page - 1) * limit;

  const [chats, total] = await Promise.all([
    this.find({ participants: userId, isActive: true })
      .populate('participants', 'firstName lastName avatar role')
      .populate('bookingId', 'bookingId type status')
      .sort({ updatedAt: -1 })
      .skip(skip)
      .limit(limit),
    this.countDocuments({ participants: userId, isActive: true }),
  ]);

  const chatsWithUnread = chats.map(chat => {
    const chatObj = chat.toObject();
    chatObj.unreadCount = chat.unreadCount?.get(userId.toString()) || 0;
    return chatObj;
  });

  return {
    chats: chatsWithUnread,
    pagination: { page, limit, total, totalPages: Math.ceil(total / limit) },
  };
};

// Pre-save: Update lastMessageAt
chatSchema.pre('save', function (next) {
  if (this.isModified('lastMessage.sentAt')) {
    this.updatedAt = new Date();
  }
  next();
});

const Chat = mongoose.model('Chat', chatSchema);
const Message = mongoose.model('Message', messageSchema);

module.exports = { Chat, Message };

